USE WAREHOUSE WH_INGEST;
USE DATABASE SEC_PRICING;



-- create the table to collect rejected records
CREATE TABLE IF NOT EXISTS CORE.EOD_PRICES_REJECT (
  TRADE_DATE     DATE,
  SYMBOL         STRING,
  OPEN           NUMBER(18,6),
  HIGH           NUMBER(18,6),
  LOW            NUMBER(18,6),
  CLOSE          NUMBER(18,6),
  VOLUME         NUMBER(38,0),
  REJECT_REASON  STRING,
  _SRC_FILE      STRING,
  _INGEST_TS     TIMESTAMP_LTZ,
  REJECT_TS      TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);





-------------------- Helpers ---------------------------------------------------
-- SELECT COUNT(*) as rejected_rows FROM CORE.EOD_PRICES_REJECT;

-- SELECT * FROM CORE.EOD_PRICES_REJECT;

-- SELECT * FROM SEC_PRICING.RAW.RAW_EOD_PRICES WHERE VOLUME < 0;

-- SELECT * FROM SEC_PRICING.CORE.EOD_PRICES WHERE VOLUME < 0;

-- SELECT MAX(TRADE_DATE) FROM SEC_PRICING.CORE.EOD_PRICES;


-- TRUNCATE TABLE CORE.EOD_PRICES_REJECT

-- DELETE FROM SEC_PRICING.RAW.RAW_EOD_PRICES
-- WHERE TRADE_DATE = '2025-10-27';

-- DELETE FROM SEC_PRICING.CORE.EOD_PRICES
-- WHERE TRADE_DATE = '2025-10-27';


